version: 2

sources:
  - name: dbt-dimensions
    tables:
      - name: transactions_dimension
      - name: wallets_dimension
      - name: profiles_dimension
      - name: time-dimension
      - name: date-dimension
  - name: dbt-facts
    tables:
      - name: transactions_fact
